app/Http/routes.php
Route::get('/register', 'UserController@register')->name('register');
Route::post('/register-account', 'UserController@store')->name('register-account');
Route::get('/welcome', 'UserController@welcome')->name('welcome');
Route::get('/asd', function() {return redirect()->route('welcome')->with('isFirst', true);});

// Recover Password
Route::get('/recovery', 'UserController@recoverPassword')->name('recoverPass');
Route::post('/recovery/submit', 'UserController@recoverPasswordSubmit')->name('recoverPass.submit');

// Change Password
Route::get('/recovery/change-password', 'UserController@recoveryChangePassword')->name('recoverPass.changePass');
Route::post('/recovery/update-password', 'UserController@recoveryUpdatePassword')->name('recoverPass.updatePass');

// Livestream Access
Route::get('/livestreams/{id}', 'PageController@showLivestream')->name('livestream.show');

///////////////////////////
// AUTHENTICATION NEEDED //
///////////////////////////
Route::group(['middleware' => ['auth']], function() {
	// Email Verification
	Route::get('/verification-page/{code?}', 'EmailVerificationController@verificationForm')->name('email-verification.form');
	Route::get('/verify/{code?}', 'EmailVerificationController@verifyCode')->name('email-verification.verify');
	Route::post('/resend-code', 'EmailVerificationController@resend')->name('email-verification.resend');

	// Account
	Route::get('/account', 'UserController@index')->name('account');
	Route::get('/account/edit', 'UserController@edit')->name('account.edit');
	Route::post('/account/edit/update', 'UserController@update')->name('account.update');
	Route::get('/logout', 'UserController@logout')->name('logout');

	// Account - Order Tracking
	Route::get('/account/orders', 'UserController@orderTrackingIndex')->name('account.orders');
	Route::get('/account/orders/{id}', 'UserController@orderTrackingShow')->name('account.orders.show');
	Route::get('/account/orders/cancel/{id}', 'SalesOrderController@cancel')->name('account.orders.cancel');
	Route::get('/account/orders/{id}/upload-proof', 'SalesOrderController@uploadProof')->name('account.orders.upload_proof');
	Route::get('/account/orders/{id}/received', 'SalesOrderController@orderReceived')->name('account.orders.received');
	Route::post('/upload-proof/{id}/orders', 'SalesOrderController@postUploadProof')->name('upload-proof.orders');

	// Account - Livestreams
	Route::get('/account/livestreams', 'UserController@livestreamTrackingIndex')->name('account.livestreams');
	Route::get('/account/livestreams/{id}', 'UserController@livestreamTrackingShow')->name('account.livestreams.show');
	Route::get('/account/livestreams/cancel/{id}', 'UserController@cancelLivestream')->name('account.livestreams.cancel');
	Route::get('/account/livestreams/{id}/upload-proof', 'UserController@uploadProof')->name('account.livestreams.upload_proof');
	Route::post('/upload-proof/{id}/livestream', 'UserController@postUploadProof')->name('upload-proof.livestreams');

	// Shipping Address
	Route::post('shipping-address/store', 'ShippingAddressController@store')->name('shipping-address.store');
	Route::post('shipping-address/update/{id}', 'ShippingAddressController@update')->name('shipping-address.update');
	Route::post('shipping-address/delete/{id}', 'ShippingAddressController@delete')->name('shipping-address.delete');

	// Cart
	Route::get('/cart', 'CartController@index')->name('cart.index');
	Route::get('/cart/add/{id}', 'CartController@addToCart')->name('cart.addToCart');
	Route::get('/cart/addToExisting/{id}', 'CartController@addToExisting')->name('cart.addToExisting');
	Route::get('/cart/subtractToExisting/{id}', 'CartController@subtractToExisting')->name('cart.subtractToExisting');
	Route::get('/cart/{id}/delete', 'CartController@delete')->name('cart.delete');
	Route::get('/cart/livestream/addToExisting/{id}', 'LivestreamManagementController@addToExisting')->name('cart.livestream.addDuration');
	Route::get('/cart/livestream/subtractToExisting/{id}', 'LivestreamManagementController@subtractToExisting')->name('cart.livestream.subtractDuration');
	Route::get('/cart/livestream/{id}/delete', 'LivestreamManagementController@delete')->name('cart.livestream.delete');

	// Billing
	Route::get('/check-out', 'CheckoutController@index')->name('billing');
	Route::post('/billing-payment', 'CheckoutController@payment')->name('billing-payment');
	Route::get('/billing-payment', 'CheckoutController@showPayment')->name('billing-payment-show');
	Route::post('/billing-review', 'CheckoutController@review')->name('billing-review');
	Route::get('/billing-review', 'CheckoutController@showReview')->name('billing-review-show');
	Route::post('/billing-order', 'CheckoutController@order')->name('billing-order');
	Route::get('/billing-livestream', 'CheckoutController@livestreamBilling')->name('billing.livestream');
	Route::post('/billing-livestream/finished', 'CheckoutController@livestreamBillingDone')->name('billing.livestream.finished');

	// Livestream access
	Route::get('/livestream/{id}/delete', 'UserController@deleteLivestream')->name('livestream.delete');
	Route::post('/livestream/create', 'UserController@addLivestreamToCart')->name('livestream.create');
	Route::post('/update-options/{id}', 'UtilityFunctionController@updateLivestreamOption')->name('livestream.options.update');
	Route::post('/token-extend', function() {return csrf_token();})->name('token-extend');

	// Mailing
	Route::post('/inquiry/send', 'PageController@sendInquiry')->name('mail.inquiry.send');

	////////////////////////////////
	////////// ADMIN SIDE //////////
	////////////////////////////////
	Route::group(['middleware' => ['admin'], 'prefix' => 'admin'], function() {
		// Dashboard
		Route::get('/', 'PageController@redirectToAdmin')->name('admin');
		Route::get('/dashboard', 'PageController@adminDashboard')->name('admin.dashboard');

		// Sales Order
		Route::get('/sales-order/{id}/print', 'SalesOrderController@prints')->name('admin.sales-order.print');
		Route::get('/sales-order/{id}/accept', 'SalesOrderController@acceptProof')->name('admin.sales-order.proof.accept');
		Route::get('/sales-order/{id}/reject', 'SalesOrderController@rejectProof')->name('admin.sales-order.proof.reject');
		Route::resource('sales-order', 'SalesOrderController');

		// Store
		Route::get('/store/{store_id}/show/{id}', 'StoreController@showSalesOrder')->name('admin.store.sales-order.show');
		Route::get('/store/{store_id}/show/{id}/print', 'StoreController@printSalesOrder')->name('admin.store.sales-order.print');
		Route::resource('store', 'StoreController');
		Route::post('/store/{id}', 'StoreController@update')->name('admin.store.update');
		Route::get('/store/{id}/delete', 'StoreController@delete')->name('admin.store.delete');

		// Store-Map
		Route::get('/store/{id}/map', 'StoreController@mapShow')->name('admin.store.map.show');
		Route::get('/store/{id}/map/edit', 'StoreController@mapEdit')->name('admin.store.map.edit');
		Route::post('/store/{id}/map/update', 'StoreController@mapUpdate')->name('admin.store.map.update');

		// User-Management
		Route::resource('user-management', 'UserManagementController');
		Route::get('/user-management/{id}/delete', 'UserManagementController@delete')->name('admin.user-management.delete');
		Route::post('/user-management/{id}/update', 'UserManagementController@update')->name('admin.user-management.update');

		// Services
		Route::get('/services', 'ServicesController@index')->name('admin.services.index');
	    Route::post('/services/store', 'ServicesController@store')->name('admin.services.store');
	    Route::get('/services/{service_name}', 'ServicesController@show')->name('admin.services.show');
	    Route::get('/services/{service_name}/edit', 'ServicesController@edit')->name('admin.services.edit');
	    Route::post('/services/{id}/update', 'ServicesController@update')->name('admin.services.update');
	    // Route::get('/services/{id}/delete', 'ServicesController@delete')->name('admin.services.delete');

		// Livestream Management
		Route::resource('livestream-management', 'LivestreamManagementController');
		Route::get('/livestream-management/{id}/delete', 'LivestreamManagementController@delete')->name('admin.livestream-management.delete');
		Route::get('/livestream/{id}/approve', 'LivestreamManagementController@approve')->name('livestream.approve');
		Route::get('/livestream/{id}/cancel', 'LivestreamManagementController@cancel')->name('livestream.cancel');
		Route::get('/livestream/{id}/streaming', 'LivestreamManagementController@streaming')->name('livestream.streaming');
		Route::get('/livestream/{id}/done', 'LivestreamManagementController@done')->name('livestream.done');
		Route::get('/livestrea/options/get/{id}', 'UtilityFunctionController@getLivestreamOptions')->name('livestream.options.get');
	});

	////////////////////////////////
	////////// OWNER SIDE //////////
	////////////////////////////////
	Route::group(['middleware' => ['owner'], 'prefix' => 'owner'], function() {
		// Index
		Route::get('/', 'PageController@redirectToOwner')->name('owner');
		Route::get('/dashboard', 'PageController@ownerDashboard')->name('owner.dashboard');

		// Sales Order
		Route::get('/sales-order/{id}/print', 'OwnerSalesOrderController@prints')->name('owner.sales-order.print');
		Route::get('/sales-order/{id}/accept', 'OwnerSalesOrderController@acceptProof')->name('owner.sales-order.proof.accept');
		Route::get('/sales-order/{id}/reject', 'OwnerSalesOrderController@rejectProof')->name('owner.sales-order.proof.reject');
		Route::post('/sales-order/{id}/tracking-number/add', 'OwnerSalesOrderController@addTrackingNumber')->name('owner.sales-order.tracking_number.add');
		Route::post('/sales-order/{id}/tracking-number/update', 'OwnerSalesOrderController@updateTrackingNumber')->name('owner.sales-order.tracking_number.update');
		Route::resource('sales-order', 'OwnerSalesOrderController');

		// Category

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Http\Requests;

use App\CartItem;
use App\Product;

use DB;
use Log;
use Exception;

class CartController extends Controller
{
	protected function index() {
		return view('client.cart.index');
	}

	protected function addToCart($id) {
		$product = Product::find($id);

		if ($product == null)
			return redirect()
				->back()
				->with('flash_error', 'Product is non-existent...');

		if ($product->status == 1) {
			try {
				DB::beginTransaction();

				if (CartItem::where('product_id', '=', $product->id)->first() != null) {
					$item = CartItem::where('user_id', '=', Auth::user()->id)
						->where('product_id', '=', $product->id)
						->first();

					$item->quantity = $item->quantity+1;
					$item->save();
				}
				else {
					CartItem::create([
						'user_id' => Auth::user()->id,
						'product_id' => $product->id,
						'quantity' => 1
					]);
				}

				DB::commit();
			} catch (Exception $e) {
				Log::error($e);
				DB::rollback();

				return redirect()
					->back()
					->with('flash_error', 'Something went wrong, please try again later.');
			}
		}

		return redirect()
			->back()
			->with('flash_success', 'Succesfully added item to cart.');
	}

	protected function addToExisting($id) {
		try {
			DB::beginTransaction();

			$item = CartItem::find($id);

			if (($item->quantity + 1) > Product::find($item->product_id)->inventory) {
				return redirect()
					->back()
					->with('flash_error', 'Cannot add more than the current available stock.');
			}

			$item->quantity += 1;
			$item->save();

			DB::commit();
		} catch (Exception $e) {
			Log::error($e);
			DB::rollback();

			return redirect()
				->back()
				->with('flash_error', 'Something went wrong, please try again later.');
		}

		return redirect()
			->back()
			->with('flash_success', 'Successfully increased amount of item to cart.');
	}

	protected function subtractToExisting($id) {
		$delete = false;
		try {
			DB::beginTransaction();

			$item = CartItem::find($id);

			if (($item->quantity - 1) == 0) {
				$item->delete();
				$delete = true;
			}
			else {
				$item->quantity -= 1;
				$item->save();
			}

			DB::commit();
		} catch (Exception $e) {
			Log::error($e);
			DB::rollback();

			return redirect()
				->back()
				->with('flash_error', 'Something went wrong, please try again later.');
		}

		if ($delete)
			return redirect()
				->back()
				->with('flash_message', 'Removed the item from cart.');

		return redirect()
			->back()
			->with('flash_success', 'Successfully decreased amount of item to cart.');
	}

	protected function delete($id) {
		$item = CartItem::find($id);
		$itemName = $item->product->product_name;

		try {
			DB::beginTransaction();
			
			$item->delete();

			DB::commit();
		} catch (Exception $e) {
			Log::error($e);
			DB::rollback();

			return redirect()
				->back()
				->with('flash_error', 'Something went wrong, please try again later.');
		}

		return redirect()
			->back()
			->with('flash_success', 'Successfully removed "' . $itemName . '"" from the cart.');
	}
}

resources/views/client/cart/index.blade.php
@extends('template.client')

@section('title', 'Home')

@section('page-css')
<link rel="stylesheet" href="/css/cart.css" >
@endsection

@section('css')
<style type="text/css">
	.cart-tr-border {
		border-bottom-style: dashed!important;
		border-bottom-width: 1.25px!important;
		border-bottom-color: #707070!important;
	}
</style>
@endsection

@section('body')
<!-- Main Content-->   
<div class="container py-5 my-5">
	@if (count(Auth::user()->cartItem) > 0 || count(Auth::user()->livestreamCart()) > 0)
	<div class="row my-5">
		<div class="col-lg-8 col-md-6">
			<h1>Cart</h1>
			
			<div class="container bg-light pt-3 pb-4 rounded">
				<h3><span class="item">Item Summary</span></h3>
				<div class="table d-grid "id="table">
					{{-- LIVESTREAMS --}}
					<h3><span class="item">Livestream Summary</span></h3>
					<table class="table-light text-center all-text-dark">
						<thead>
							<tr>
								<th>Category</th>
								<th>Price</th>
								<th>Duration</th>
								<th>Total</th>
							</tr>
						</thead>

						<tbody>
							@forelse (Auth::user()->livestreamCart() as $l)
							<tr class="cart-tr-border">
								<td>{{ ucwords($l->category == null ? 'None' : $l->category) }}</td>
								<td>&#8369;{{number_format(100, 2)}}</td>
								<td>
									<div class="d-flex flex-row justify-content-center">
										<a href="{{ route('cart.livestream.addDuration', [$l->id]) }}" class="mx-1 text-decoration-none">+</a>
										<span class="mx-1">{{$l->duration}}</span>
										<a href="{{ route('cart.livestream.subtractDuration', [$l->id]) }}" class="mx-1 text-decoration-none">-</a>
									</div>
								</td>
								<td style="vertical-align: middle; position: relative;">
									&#8369;{{number_format($l->price, 2)}}
									<a href="{{ route('cart.livestream.delete', [$l->id]) }}" style="position: absolute; bottom: 0; right: 0;" class="text-decoration-none"><i class="far fa-times-circle"></i></a>
								</td>
							</tr>
							@empty
							<tr>
								<td colspan="5" class="text-center">Nothing to show...</td>
							</tr>
							@endforelse
						</tbody>
					</table>

					{{-- PRODUCTS --}}
					<h3><span class="item">Item Summary</span></h3>
					<table class="table-light text-center all-text-dark">
						<thead>
							<tr>
								<th class="text-left">Item</th>
								<th>Price</th>
								<th>Qty</th>
								<th>Total</th>
							</tr>
						</thead>

						<tbody>
							@forelse (Auth::user()->cartItem as $c)
							<tr class="cart-tr-border">
								<td class="text-left d-flex flex-row align-items-center">
									<img src="uploads/products/{{$c->product->category->category_name}}/{{$c->product->image_name}}" alt="" class="w-25 img-fluid border">
									<span class="item_name ml-2" >{{$c->product->product_name}}</span>
								</td>
								<td style="vertical-align: middle;">&#8369;{{number_format($c->product->selling_price, 2)}}</td>
								<td style="vertical-align: middle;">
									<div class="d-flex flex-row">
										<a href="{{ route('cart.addToExisting', [$c->id]) }}" class="mx-1 text-decoration-none">+</a>
										<span class="mx-1">{{$c->quantity}}</span>
										<a href="{{ route('cart.subtractToExisting', [$c->id]) }}" class="mx-1 text-decoration-none">-</a>
									</div>
								</td>
								<td style="vertical-align: middle; position: relative;">
									&#8369;{{number_format($c->total(), 2)}}
									<a href="{{ route('cart.delete', [$c->id]) }}" style="position: absolute; bottom: 0; right: 0;" class="text-decoration-none"><i class="far fa-times-circle"></i></a>
								</td>
							</tr>
							@empty
							<tr>
								<td colspan="5" class="text-center">Nothing to show...</td>
							</tr>
							@endforelse
						</tbody>
					</table>
				</div>
			</div>
		</div>

		<div class="col-lg-4 col-md-6">
			<div class="container bg-light mt-3 py-3 d-grid rounded">
				<h4><span class="item">Order Summary</span></h4> 
				<h3><span class="item">&#8369;{{number_format(Auth::user()->cartTotal() + Auth::user()->livestreamTotal(), 2)}}</span></h3><br>
				{{Auth::user()->livestreamTotal()}}
				@if (count(Auth::user()->livestreamCart()) > 0)
				<a href="{{ route('billing.livestream') }}" class="btn btn-lg btn-dark">Go to Checkout</a>
				@else
				<a href="{{ route('billing') }}" class="btn btn-lg btn-dark">Go to Checkout</a>
				@endif
			</div>

			<div class="container mt-3">
				<h5>Accepted Payment Methods</h5>
				<img src="images/UI/Pay_COD.png" alt="" class="pay img-fluid">
				<img src="images/UI/Pay_Bank.png" alt="" class="pay img-fluid">
				<img src="images/UI/Pay_Paypal.png" alt="" class="pay img-fluid">
				<img src="images/UI/Pay_GCash.png" alt="" class="pay img-fluid">
			</div>
		</div>
	</div>
	@else
	<section class="py-5 my-5">
		<div class="container py-5">
			<div class="row align-items-center text-center my-5">
				<img src="images/UI/cart-x.svg" alt="" width="100px" height="100px">
				<h3 class="mt-5"> <b>YOUR CART IS EMPTY!</b></h3>
				<p>Start shopping to fill your cart with your desired items.</p>
				<div class="d-grid gap-2 col-6 mx-auto">
					<a href="{{ route('store.index') }}" class="btn-lg btn-light btn-outline-dark text-decoration-none">SHOP NOW</a>
				</div>
			</div>
		</div>
	</section>
	@endif
</div>
@endsection